### PR TITLE
RGB Chart

### LINKED ISSUE #181: Interface for RBG Values
A partial view should be added to the photo/index page that shows a pie chart of RBG colors.

### PR DESCRIPTION
**Pull request by zmchristensen**
Added RGB partial to resolve #181.

### CODE REVIEW

**Comment by icotting** [comment]
Those colors are little harsh. How about: 

Red - #ab3d33
Green - #58a64c
Blue - #373fa9

**Comment by icotting** [comment]
Also, let's go with Image Color Profile rather than analysis.

**Comment by zmchristensen** [comment]
screenshot 2015-05-14 10 47 04

**Comment by icotting** [comment]
Better

**Pull request merged**
